### ISSUE TITLE
Workflows - Test small data sets for workflows (mg_annotation)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/mg_annotation#5]
create a small test data set with expected outcome if workflow run is successful

link test results to this issue

**Comment by hubin-keio** [comment]
Shane, please point me the location of two test data sets (one smaller set for quick test and one small realistic data set for thorough test) and the expected outcome from each workflow run in JSON format. I will work on a unit-test-like solution for testing. Thank you.

**Comment by scanon** [comment]
I've been using these...

/global/cfs/cdirs/m3408/aim2/testing/2021-01-22/241870
/global/cfs/cdirs/m3408/aim2/testing/2021-01-22/241871

But I need to verify with Marcel if those can be made public or not.

**Comment by scanon** [comment]
The JSON output is not currently part of the pipeline.

**Comment by mhuntemann** [comment]
No, those datasets can not be made public.
I just picked them, since they were some of the most recent ones processed with the latest version of the pipeline at that time.
They were only meant to be used for internal comparison.
If we need something that we can make public, maybe Reddy or Amy can help us identify a few different sized metagenomes that are actually published and completely free to use.

**Comment by scanon** [comment]
I'm using some data sets from Stegen that were already part of NMDC.  So those should be fine.  I'll make a PR that adds the new testing WDLs.

**Comment by ssarrafan** [comment]
@scanon and @hubin-keio can I move this to the May sprint or do you consider this to be completed?

**Comment by ssarrafan** [comment]
Moving to May sprint.  Please close if this is done.
